<a href="https://colab.research.google.com/github/Al-Amin-01/LearnPytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!nvidia-smi


Sat Dec  9 16:52:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Import torch**


In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


**Introduction to Tensors**

In [7]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
#vector
vector=torch.tensor([1,2])
vector

tensor([1, 2])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
#MATRIX
MATRIX=torch.tensor([[1,2],
                     [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR=torch.tensor([[[1,2,2],
                      [4,5,2]],
                      [[7,8,2],
                       [9,0,2]]])
TENSOR

tensor([[[1, 2, 2],
         [4, 5, 2]],

        [[7, 8, 2],
         [9, 0, 2]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 2, 3])

In [19]:
TENSOR[0][1][0]

tensor(4)

In [20]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2305, 0.6030, 0.2116, 0.3206],
        [0.6816, 0.3634, 0.4345, 0.9038],
        [0.4262, 0.1399, 0.0905, 0.5650]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
image_tensor=torch.rand(224,224,3)
image_tensor.shape,image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

zeros and ones


In [24]:
zeros=torch.zeros(3,3)
zeros


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
zeros.ndim

2

In [26]:
ones=torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
a=torch.arange(1,30,5)
a

tensor([ 1,  6, 11, 16, 21, 26])

In [29]:
b=torch.zeros_like(input=a)
b

tensor([0, 0, 0, 0, 0, 0])

In [30]:
c=torch.rand(2,2)
c

tensor([[0.3584, 0.1924],
        [0.5045, 0.9891]])

In [31]:
tens=torch.tensor([1.,2.,3.],
                  dtype=None,
                  device=None,
                  requires_grad=False)
tens

tensor([1., 2., 3.])

In [32]:
tens.dtype

torch.float32

In [33]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2855, 0.2112, 0.7746, 0.0192],
        [0.7622, 0.7719, 0.9184, 0.8480],
        [0.0721, 0.2835, 0.2708, 0.6663]])

In [34]:
print(some_tensor)
print(f"data type:{some_tensor.dtype}")
print(f"data shape:{some_tensor.shape}")
print(f"device:{some_tensor.device}")

tensor([[0.2855, 0.2112, 0.7746, 0.0192],
        [0.7622, 0.7719, 0.9184, 0.8480],
        [0.0721, 0.2835, 0.2708, 0.6663]])
data type:torch.float32
data shape:torch.Size([3, 4])
device:cpu


In [35]:
addten=torch.zeros(5,dtype=torch.int16)
addten

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [36]:
addten+12

tensor([12, 12, 12, 12, 12], dtype=torch.int16)

In [37]:
addten-torch.tensor([1,2,3,4,5])

tensor([-1, -2, -3, -4, -5])

In [38]:
addten*3

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [39]:
addten/4

tensor([0., 0., 0., 0., 0.])

In [40]:
%%time
jim=torch.tensor([1,2,3])

print(f"tensor*tensor={torch.matmul(jim,jim)}")

tensor*tensor=14
CPU times: user 614 µs, sys: 741 µs, total: 1.35 ms
Wall time: 1.45 ms


In [41]:
torch.rand(2,2) @ torch.rand(2,3)

tensor([[0.3498, 0.6321, 0.2261],
        [0.5241, 0.6318, 0.1949]])

In [42]:
ten_A=torch.tensor([[1,2],
                    [3,4],
                    [5,6]])
ten_B=torch.tensor([[7,8],
                    [9,1],
                    [1,2]])


In [43]:
print(ten_A)
print(ten_A.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [44]:
ten_A @ ten_B.T

tensor([[23, 11,  5],
        [53, 31, 11],
        [83, 51, 17]])

In [45]:
tens=torch.arange(0,100,10)
tens

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
tens.min()

tensor(0)

In [47]:
tens.max()

tensor(90)

In [48]:
tens.dtype

torch.int64

In [49]:
tens.type(torch.float32).mean()

tensor(45.)

In [50]:
tens.sum()

tensor(450)

In [51]:
tens.argmin()

tensor(0)

In [52]:
tens.argmax()

tensor(9)

In [53]:
tenx=torch.arange(1.,10.)
tenx.shape

torch.Size([9])

In [54]:
tenx_reshaped=tenx.reshape(3,3)
tenx_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [55]:
tenx_stacked=torch.stack([tenx,tenx,tenx,tenx],dim=0)
tenx_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
tenx_stacked=torch.stack([tenx,tenx,tenx,tenx],dim=1)
tenx_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [57]:
print(f"Before unsqueezing tensor:{tenx}")
print(f"Before unsqueezing shape:{tenx.shape}")
tenx_unsqueezed=tenx.unsqueeze(dim=0)
print(f"After unsqueezing tensor:{tenx_unsqueezed}")
print(f"After unsqueezing shape:{tenx_unsqueezed.shape}")
tenx_squeezed=tenx_unsqueezed.squeeze()
print(f"After squeezing tensor:{tenx_squeezed}")
print(f"After squeezing shape:{tenx_squeezed.shape}")

Before unsqueezing tensor:tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Before unsqueezing shape:torch.Size([9])
After unsqueezing tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
After unsqueezing shape:torch.Size([1, 9])
After squeezing tensor:tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
After squeezing shape:torch.Size([9])


In [58]:
imt=torch.rand(224,224,3)
imt_permuted=imt.permute(2,0,1)
print(f"original shape:{imt.shape}")
print(f"permuted shape:{imt_permuted.shape}")

original shape:torch.Size([224, 224, 3])
permuted shape:torch.Size([3, 224, 224])


In [59]:
tx=torch.arange(1,10).reshape(1,3,3)
tx,tx.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
tx[0,:,1]

tensor([2, 5, 8])

In [61]:
tx[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
tx[0,1,:]

tensor([4, 5, 6])

In [63]:
ar=np.arange(1.0,8.0)
ten_ar=torch.from_numpy(ar)
ar,ten_ar

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [64]:
ar.dtype

dtype('float64')

In [65]:
arr=ten_ar.numpy()
arr

array([1., 2., 3., 4., 5., 6., 7.])

In [66]:
rta=torch.rand(3,4)
rtb=torch.rand(3,4)
print(rta)
print(rtb)
print(rta==rtb)

tensor([[0.5866, 0.5069, 0.8938, 0.7064],
        [0.3836, 0.7103, 0.4336, 0.0342],
        [0.3137, 0.5230, 0.3709, 0.1622]])
tensor([[0.6102, 0.2757, 0.3207, 0.4123],
        [0.5333, 0.5806, 0.9811, 0.8141],
        [0.2069, 0.0108, 0.3901, 0.1155]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [67]:
#use randomseed
RANDOM_SEED=300
torch.manual_seed(RANDOM_SEED)
rta1=torch.rand(3,4)
torch.manual_seed(300)
rtb1=torch.rand(3,4)
print(rta1)
print(rtb1)
print(rta1==rtb1)

tensor([[0.4874, 0.4340, 0.5817, 0.7601],
        [0.4848, 0.4432, 0.4386, 0.1852],
        [0.7159, 0.2959, 0.2039, 0.1400]])
tensor([[0.4874, 0.4340, 0.5817, 0.7601],
        [0.4848, 0.4432, 0.4386, 0.1852],
        [0.7159, 0.2959, 0.2039, 0.1400]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [68]:
!nvidia-smi


Sat Dec  9 16:52:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [69]:
torch.cuda.is_available()

True

In [71]:
device="cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [72]:
torch.cuda.device_count()

1

In [73]:
tenc=torch.tensor([1,2,3])
print(tenc,tenc.device)

tensor([1, 2, 3]) cpu


In [78]:
teng=tenc.to(device)
teng.device

device(type='cuda', index=0)

In [86]:
tengbc=teng.cpu()
tengbc

tensor([1, 2, 3])